from typing import Protocol

class BaseTool(Protocol):
    def on_mouse_down(self, event): ...
    def on_mouse_move(self, event): ...
    def on_mouse_up(self, event): ...
    def on_page_rendered(self): ...
    def deactivate(self): ...